# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_spaceplugin'),
        ('swingtime', '__first__'),
        ('spaces_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='spacescalendar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spacescalendar',
            name='space',
        ),
        migrations.AddField(
            model_name='spacescalendar',
            name='spaceplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spaces.SpacePlugin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces_calendar.SpacesCalendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swingtime.Event'),
        ),
    ]
