# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-17 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_calendar', '0002_auto_20151111_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swingtime.Event'),
        ),
    ]
