# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_calendar', '0003_auto_20151117_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
