# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces_calendar', '0004_auto_20160111_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
